-
  type: cohesion_component_category
  export:
    uuid: ed6dd78b-28b2-4b82-98fa-ea11d4866ad6
    langcode: en
    status: true
    dependencies: {  }
    id: cpt_cat_template_components
    label: 'Template components'
    json_values: '{}'
    json_mapper: '{}'
    last_entity_update: entityupdate_0027
    locked: false
    modified: false
    selectable: true
    class: category-14
    weight: -5
