name: 'Acquia Drupal Startekit Document'
description: 'Provides a Document media type and related configuration.'
type: 'Starterkit addon'
install:
  # Contrib
  - acquia_cms_document
config:
  import:
    acquia_cms_document: '*'
    file: '*'
    media: '*'
    media_library: '*'
    taxonomy: '*'
    field_group: '*'
