name: 'Acquia Drupal Startekit Basic HTML editor'
type: 'Acquia Drupal Startekit'
description: 'Enhances the Basic HTML editor with better linking and media support.'
install:
  - ckeditor5
  - linkit
  - media_library
  - node
  - user
config:
  import:
    linkit:
      - image.style.linkit_result_thumbnail
    user:
      - user.role.authenticated
  actions:
    user.role.authenticated:
      grantPermission: 'use text format basic_html'
