version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
      # Use Indian Standard Time (UTC +05:30)
      timezone: "Asia/Kolkata"
      time: "09:00"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
    versioning-strategy: auto
    ignore:
      # We don't want check for acquia_cms modules.
      - dependency-name: "drupal/acquia_cms*"
    # Raise pull requests for version updates
    # to pip against the `develop` branch
    target-branch: "develop"

  - package-ecosystem: "composer"
    directory: "/modules/acquia_cms_audio"
    schedule:
      interval: "daily"
      # Use Indian Standard Time (UTC +05:30)
      timezone: "Asia/Kolkata"
      time: "09:00"
    ignore:
      # We don't want check for acquia_cms modules.
      - dependency-name: "drupal/acquia_cms*"
    versioning-strategy: auto
    # Raise pull requests for version updates
    # to pip against the `develop` branch
    target-branch: "develop"

  - package-ecosystem: "composer"
    directory: "/modules/acquia_cms_common"
    schedule:
      interval: "daily"
      # Use Indian Standard Time (UTC +05:30)
      timezone: "Asia/Kolkata"
      time: "09:00"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
    versioning-strategy: auto
    ignore:
      # We don't want check for acquia_cms modules.
      - dependency-name: "drupal/acquia_cms*"
    # Raise pull requests for version updates
    # to pip against the `develop` branch
    target-branch: "develop"

  - package-ecosystem: "composer"
    directory: "/modules/acquia_cms_component"
    schedule:
      interval: "daily"
      # Use Indian Standard Time (UTC +05:30)
      timezone: "Asia/Kolkata"
      time: "09:00"
    ignore:
      # We don't want check for acquia_cms modules.
      - dependency-name: "drupal/acquia_cms*"
    versioning-strategy: auto
    # Raise pull requests for version updates
    # to pip against the `develop` branch
    target-branch: "develop"

  - package-ecosystem: "composer"
    directory: "/modules/acquia_cms_dam"
    schedule:
      interval: "daily"
      # Use Indian Standard Time (UTC +05:30)
      timezone: "Asia/Kolkata"
      time: "09:00"
    ignore:
      # We don't want check for acquia_cms modules.
      - dependency-name: "drupal/acquia_cms*"
    versioning-strategy: auto
    # Raise pull requests for version updates
    # to pip against the `develop` branch
    target-branch: "develop"

  - package-ecosystem: "composer"
    directory: "/modules/acquia_cms_headless"
    schedule:
      interval: "daily"
      # Use Indian Standard Time (UTC +05:30)
      timezone: "Asia/Kolkata"
      time: "09:00"
    ignore:
      # We don't want check for acquia_cms modules.
      - dependency-name: "drupal/acquia_cms*"
    versioning-strategy: auto
    # Raise pull requests for version updates
    # to pip against the `develop` branch
    target-branch: "develop"

  - package-ecosystem: "composer"
    directory: "/modules/acquia_cms_image"
    schedule:
      interval: "daily"
      # Use Indian Standard Time (UTC +05:30)
      timezone: "Asia/Kolkata"
      time: "09:00"
    ignore:
      # We don't want check for acquia_cms modules.
      - dependency-name: "drupal/acquia_cms*"
    versioning-strategy: auto
    # Raise pull requests for version updates
    # to pip against the `develop` branch
    target-branch: "develop"

  - package-ecosystem: "composer"
    directory: "/modules/acquia_cms_person"
    schedule:
      interval: "daily"
      # Use Indian Standard Time (UTC +05:30)
      timezone: "Asia/Kolkata"
      time: "09:00"
    ignore:
      # We don't want check for acquia_cms modules.
      - dependency-name: "drupal/acquia_cms*"
    versioning-strategy: auto
    # Raise pull requests for version updates
    # to pip against the `develop` branch
    target-branch: "develop"

  - package-ecosystem: "composer"
    directory: "/modules/acquia_cms_place"
    schedule:
      interval: "daily"
      # Use Indian Standard Time (UTC +05:30)
      timezone: "Asia/Kolkata"
      time: "09:00"
    ignore:
      # We don't want check for acquia_cms modules.
      - dependency-name: "drupal/acquia_cms*"
    versioning-strategy: auto
    # Raise pull requests for version updates
    # to pip against the `develop` branch
    target-branch: "develop"

  - package-ecosystem: "composer"
    directory: "/modules/acquia_cms_search"
    schedule:
      interval: "daily"
      # Use Indian Standard Time (UTC +05:30)
      timezone: "Asia/Kolkata"
      time: "09:00"
    ignore:
      # We don't want check for acquia_cms modules.
      - dependency-name: "drupal/acquia_cms*"
    versioning-strategy: auto
    # Raise pull requests for version updates
    # to pip against the `develop` branch
    target-branch: "develop"

  - package-ecosystem: "composer"
    directory: "/modules/acquia_cms_site_studio"
    schedule:
      interval: "daily"
      # Use Indian Standard Time (UTC +05:30)
      timezone: "Asia/Kolkata"
      time: "09:00"
    ignore:
      # We don't want check for acquia_cms modules.
      - dependency-name: "drupal/acquia_cms*"
    versioning-strategy: auto
    # Raise pull requests for version updates
    # to pip against the `develop` branch
    target-branch: "develop"

  - package-ecosystem: "composer"
    directory: "/modules/acquia_cms_starter"
    schedule:
      interval: "daily"
      # Use Indian Standard Time (UTC +05:30)
      timezone: "Asia/Kolkata"
      time: "09:00"
    ignore:
      # We don't want check for acquia_cms modules.
      - dependency-name: "drupal/acquia_cms*"
    versioning-strategy: auto
    # Raise pull requests for version updates
    # to pip against the `develop` branch
    target-branch: "develop"

  - package-ecosystem: "composer"
    directory: "/modules/acquia_cms_toolbar"
    schedule:
      interval: "daily"
      # Use Indian Standard Time (UTC +05:30)
      timezone: "Asia/Kolkata"
      time: "09:00"
    ignore:
      # We don't want check for acquia_cms modules.
      - dependency-name: "drupal/acquia_cms*"
    versioning-strategy: auto
    # Raise pull requests for version updates
    # to pip against the `develop` branch
    target-branch: "develop"

  - package-ecosystem: "composer"
    directory: "/modules/acquia_cms_tour"
    schedule:
      interval: "daily"
      # Use Indian Standard Time (UTC +05:30)
      timezone: "Asia/Kolkata"
      time: "09:00"
    ignore:
      # We don't want check for acquia_cms modules.
      - dependency-name: "drupal/acquia_cms*"
    versioning-strategy: auto
    # Raise pull requests for version updates
    # to pip against the `develop` branch
    target-branch: "develop"

  - package-ecosystem: "composer"
    directory: "/modules/sitestudio_config_management"
    schedule:
      interval: "daily"
      # Use Indian Standard Time (UTC +05:30)
      timezone: "Asia/Kolkata"
      time: "09:00"
    ignore:
      # We don't want check for acquia_cms modules.
      - dependency-name: "drupal/acquia_cms*"
    versioning-strategy: auto
    # Raise pull requests for version updates
    # to pip against the `develop` branch
    target-branch: "develop"

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
      # Use Indian Standard Time (UTC +05:30)
      timezone: "Asia/Kolkata"
      time: "09:00"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
    versioning-strategy: auto
    # Raise pull requests for version updates
    # to pip against the `develop` branch
    target-branch: "1.5.x"

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
      # Use Indian Standard Time (UTC +05:30)
      timezone: "Asia/Kolkata"
      time: "09:00"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
    versioning-strategy: auto
    # Raise pull requests for version updates
    # to pip against the `develop` branch
    target-branch: "2.0.x"
