<?php

/**
 * @file
 * Contains hook implementations for acquia_cms module.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function acquia_cms_form_user_login_form_alter(array &$form) {
  if (Drupal::config('acquia_cms.settings')->get('user_login_redirection')) {
    $form['#submit'][] = '\Drupal\acquia_cms\RedirectHandler::submitForm';
  }
}

/**
 * Prepares variables for maintenance page templates.
 *
 * Default template: maintenance-page.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - content - An array of page content.
 *
 * @see template_preprocess_maintenance_page()
 */
function acquia_cms_preprocess_maintenance_page(array &$variables) {
  $variables['#attached']['library'][] = 'seven/install-page';
  $variables['#attached']['library'][] = 'acquia_claro/install-page';
  $acquia_cms_path = \Drupal::service('extension.list.profile')->getPath('acquia_cms');
  $variables['install_page_logo_path'] = '/' . $acquia_cms_path . '/acquia_cms.png';
}

/**
 * Update config ignore settings.
 */
function acquia_cms_update_8001() {
  $config = \Drupal::configFactory()->getEditable('config_ignore.settings');
  // Get existing ignore config and append the new one.
  $existing_ignore_config = $config->get('ignored_config_entities');
  $new_ignore_config = [
    'cohesion.settings',
    'purge.plugins',
    'purge.logger_channels',
  ];
  $updated_ignore_config = array_unique(array_merge($existing_ignore_config, $new_ignore_config));
  $config->set('ignored_config_entities', $updated_ignore_config);
  $config->set('enable_export_filtering', TRUE);
  $config->save(TRUE);
}

/**
 * Uninstall page_cache module.
 */
function acquia_cms_update_8002() {
  if (\Drupal::moduleHandler()->moduleExists('page_cache')) {
    \Drupal::service('module_installer')->uninstall(['page_cache']);
  }
}
