# This file is used by Acquia Pipelines continuous integration. Upon success, an
# artifact is deployed to the `orionacms` subscription on Acquia Cloud.
variables:
  global:
    GITHUB_OAUTH_TOKEN:
      secure: 2acBhv/qQ9I4jej4N1JrYZ5xZ5979GqdkKhUedLezguYzdpyy/y0kFN0GgclFkqYM+/SUe+P76qg/VGkCIZ96swRvVAtmFroHjKoknCkdD4oRV+tr/LQyIUJn1+aCtsUXH7t2AkXF/ZQudcAd0/V/cv+pdB6LT7vkkCiD3IvmaaS0NfU3pe7rN7RNsURCXr2ssaJQYz9//e30w2M+oxoVzR8RO0U5KpNTuFnPcPYXprfOzieeEIOFSf+xsx1q33w71HxVHJ0zptrDApMg3GNUYnpVQVFd37ddB6QtntKjC3NWvlfZmq5LF7T4ten8V9Z92yqFFIVC+GORqKDXg9maXLBqfSQE8+IEuo4NPZapHqcqpvA9yL+CNA2Ia7cUDArCeFwH3dMQ5vX1sJnVjjCF3kuiU6OmvHdJUmnNpckOpElykLzq7jX2XIUEOP8cw8pXz6wI3tLg3cjzTjEAPXztV0KZYn4asuLz08xcKL3ibDE9arLDdURuGadoPkUImTP0EYbm8LWPPge3IopNk2LbpXVFZ8ULFibG4TdGse90Ynid484veajLldWXu9+WNndw5XFki6U6862w7BGaahzPl2TX/Ga6SeSntnYQlQy1nNDorbf70kzIDJw1C/l3dQpyzaK3sauUS3oAy37tw5x416e0/iDkCmoNrASx51BYLLQh0=4agk8+AwN+7+N+611oSLjMiIPrieLROvimxEI/tEt5vTy96eHU25b3pK8I66lLS4wSYOPig0wXAp7yc4KfiTXKNQdy+YX9x2reHzNRigEC0U1ervcSqFnP6tYSIpInd8bQs3C1LPGYcBmcUoMw8z1AH31uGqvmQGbCvmWVLlvD4=
version: 1.3.0
services:
  - composer:
      version: 2
  - php:
      version: 7.4

events:
  build:
    steps:
      - setup:
          type: script
          script:
            - composer validate --no-check-all --ansi --no-interaction
            - composer config -g github-oauth.github.com "$GITHUB_OAUTH_TOKEN"
            - composer install
            - mkdir -p docroot/profiles/acquia_cms
            - composer archive --format zip --file acquia_cms
            - unzip acquia_cms.zip -d docroot/profiles/acquia_cms
            # The acquia_cms_development module is ignored for export in .gitattributes,
            # but we DO want to deploy it to our Cloud environment for testing.
            # We can probably remove this, along with the acquia_cms_development module
            # itself, once we have a permanent demo site in place.
            # - cp -R modules/acquia_cms_development docroot/profiles/acquia_cms/modules
            - cp config/optional/views.view.acquia_search.yml docroot/profiles/acquia_cms/config/optional
      - cleanup:
          type: script
          script:
            - rm acquia_cms.zip
            # Prepare settings.php with the minimum required for Cloud.
            - chmod -R +w docroot/sites/default
            - cp docroot/sites/default/default.settings.php docroot/sites/default/settings.php
            # Clear any config directories that Cloud tries to set in the include file.
            - echo "\$config_directories = [];" >> docroot/sites/default/settings.php
            # Use the existing `config` directory we already have. Cloud gets confused
            # because we already have a config directory above docroot and manipulating it
            # in Pipelines doesn't seem to work. This deployment is ephemeral, so using
            # the existing config directory isn't a problem.
            - echo "\$config_directories['sync'] = '../config';" >> docroot/sites/default/settings.php
