# This file is used by Acquia Pipelines continuous integration. Upon success, an
# artifact is deployed to the `orionacms` subscription on Acquia Cloud.
version: 1.3.0
services:
  - composer:
      version: 2
  - php:
      version: 8.2

events:
  build:
    steps:
      - setup:
          type: script
          script:
            - composer validate --no-check-all --ansi --no-interaction
            - composer install
            # Create symlink directory for multisite headless and community.
            - cd docroot/sites
            - ln -s default headless
            - ln -s default community
            - mkdir drstest
            - mkdir multisite
            - cd -
      # Commenting as it's no longer needed and this is failing deployment.
      # - front-end:
      #    type: script
      #    script:
      #      - cd docroot/themes/contrib/acquia_claro
      #      - npm install
      #      - npm run build
      #      - cd -
      - cleanup:
          type: script
          script:
            # Prepare settings.php with the minimum required for Cloud.
            - chmod -R +w docroot/sites/default
            - chmod -R +w docroot/sites/drstest
            - chmod -R +w docroot/sites/multisite
            - cp docroot/sites/default/default.settings.php docroot/sites/default/settings.php
            - cp docroot/sites/default/default.settings.php docroot/sites/drstest/settings.php
            - cp docroot/sites/default/default.settings.php docroot/sites/multisite/settings.php
            # Clear any config directories that Cloud tries to set in the include file.
            - echo "\$config_directories = [];" >> docroot/sites/default/settings.php
            # Use the existing `config` directory we already have. Cloud gets confused
            # because we already have a config directory above docroot and manipulating it
            # in Pipelines doesn't seem to work. This deployment is ephemeral, so using
            # the existing config directory isn't a problem.
            - echo "\$config_directories['sync'] = '../config';" >> docroot/sites/default/settings.php
