<?php

/**
 * @file
 * Contains hook implementations for acquia_cms module.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function acquia_cms_preprocess_status_report_general_info(&$variables) {
  $extensionInfo = \Drupal::service('extension.list.module')->getExtensionInfo('acquia_cms');
  $variables['acquia_cms']['value'] = $extensionInfo['version'];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function acquia_cms_form_user_login_form_alter(array &$form) {
  if (Drupal::config('acquia_cms.settings')->get('user_login_redirection')) {
    $form['#submit'][] = '\Drupal\acquia_cms\RedirectHandler::submitForm';
  }
}

/**
 * Prepares variables for maintenance page templates.
 *
 * Default template: maintenance-page.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - content - An array of page content.
 *
 * @see template_preprocess_maintenance_page()
 */
function acquia_cms_preprocess_maintenance_page(array &$variables) {
  $variables['#attached']['library'][] = 'seven/install-page';
  $variables['#attached']['library'][] = 'acquia_claro/install-page';
  $acquia_cms_path = \Drupal::service('extension.list.module')->getPath('acquia_cms');
  $variables['install_page_logo_path'] = '/' . $acquia_cms_path . '/acquia_cms.png';
}
