name: 'Acquia Drupal Startekit Media'
description: 'An media model provides Audio, Document, Image, Video media types.'
type: 'Starterkit addon'
recipes:
  - acquia_drupal_starterkit_document
  - acquia_drupal_starterkit_image
  - acquia_drupal_starterkit_remote_audio
  - acquia_drupal_starterkit_remote_video
