name: 'Acquia Drupal Startekit Media'
description: 'An media model provides Audio, Document, Image, Video media types.'
type: 'Starterkit addon'
install:
  - field_group
  - file
  - focal_point
  - image
  - imce
  - media
  - media_entity_soundcloud
  - media_library
  - taxonomy
config:
  import:
    field_group: '*'
    file: '*'
    focal_point: '*'
    image: '*'
    imce: '*'
    media: '*'
    media_entity_soundcloud: '*'
    media_library: '*'
    taxonomy: '*'
