#!/usr/bin/env bash

## Install required modules for Acquia CMS.
##
## Usage: fin acms

#-------------------------- Helper functions -----------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

#-------------------------- END: Helper functions ------------------------

echo -e "${green}Enabling Acquia CMS modules..."
fin exec drush en acquia_cms_core acquia_cohesion -y
