display:
  default:
    display_options:
      footer:
        area:
          id: area
          table: views
          field: area
          relationship: none
          group_type: group
          admin_label: ''
          empty: false
          tokenize: false
          content:
            value: "<div>\r\n  <a href=\"\" class=\"coh-style-button-solid\" target=\"_self\">VIEW ARCHIVED EVENTS </a>\r\n</div>"
            format: cohesion
          plugin_id: text
