display:
  default:
    display_plugin: default
    id: default
    display_title: Master
    position: 0
    display_options:
      style:
        options:
          master_template: master_template
