display:
  default:
    display_plugin: default
    id: default
    display_title: Master
    position: 0
    display_options:
      access:
        type: perm
        options:
          perm: 'access content'
      cache:
        type: search_api_tag
        options: {  }
      query:
        type: views_query
        options:
          bypass_access: false
          skip_access: false
          preserve_facet_query_args: false
      exposed_form:
        type: basic
        options:
          submit_button: Apply
          reset_button: false
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          expose_sort_order: true
          sort_asc_label: Asc
      style:
        type: cohesion_layout
        options:
          views_template: view_tpl_people
          master_template: master_template
