name: 'Acquia Drupal Startekit Low-Code'
description: 'The low-code starter kit will install Acquia CMS with Site Studio and a UIkit. It provides drag and drop content authoring and low-code site building. An optional content model can be added in the installation process.'
type: 'Starterkit'
recipes:
  - acquia_drupal_starterkit_community
install:
  # Contrib
  - acquia_cms_site_studio
