name: 'Acquia Drupal Startekit Demo Content'
description: "Provides integration between your Drupal site and Acquia's hosted search service."
type: 'Starterkit addon'
recipes:
  - acquia_drupal_starterkit_content_model
  - acquia_drupal_starterkit_media
  - acquia_drupal_starterkit_search
install:
  # Contrib
  - default_content
