<?php

/**
 * @file
 * Install, update and uninstall functions for the acquia_cms_person module.
 */

/**
 * Implements hook_install().
 */
function acquia_cms_person_install() {
  user_role_grant_permissions('content_author', [
    'create person content',
    'edit own person content',
    'delete own person content',
  ]);
  user_role_grant_permissions('content_editor', [
    'edit any person content',
    'delete any person content',
  ]);
}
