acquia_cms.settings:
  type: config_object
  label: 'Acquia CMS settings'
  mapping:
    user_login_redirection:
      type: boolean
      label: 'Enable special redirection on user login for specific roles'
