name: 'Acquia Drupal Startekit Audio'
description: 'Provides an Audio media type and related configuration.'
type: 'Starterkit addon'
install:
  # Contrib
  - acquia_cms_audio
config:
  import:
    acquia_cms_audio: '*'
    media: '*'
    media_library: '*'
    taxonomy: '*'
    media_entity_soundcloud: '*'
    field_group: '*'
