-
  type: default_module_package
  source:
    module_name: acquia_cms_site_studio
    path: config/pack_acquia_cms_core
  options:
    extra-validation: false
-
  type: default_recipe_package
  source:
    dependencies:
      recipes:
        - acquia_starterkit_remote_video
    recipe_name: acquia_starterkit_remote_video
    path: site_studio/pack_acquia_starterkit_remote_video
  options:
    extra-validation: false
-
  type: default_module_package
  source:
    dependencies:
      - acquia_cms_search
    module_name: acquia_cms_search
    path: config/pack_acquia_cms_search
  options:
    extra-validation: false
-
  type: default_recipe_package
  source:
    dependencies:
      recipes:
        - acquia_starterkit_image
    recipe_name: acquia_starterkit_image
    path: site_studio/pack_acquia_starterkit_image
  options:
    extra-validation: false
-
  type: default_recipe_package
  source:
    dependencies:
      recipes:
        - acquia_starterkit_image
    recipe_name: acquia_starterkit_image
    path: site_studio/pack_acquia_starterkit_image_core
  options:
    extra-validation: false
-
  type: default_recipe_package
  source:
    dependencies:
      recipes:
        - acquia_starterkit_page
    recipe_name: acquia_starterkit_page
    path: site_studio/pack_acquia_starterkit_page
  options:
    extra-validation: false
-
  type: default_recipe_package
  source:
    dependencies:
      recipes:
        - acquia_starterkit_place
    recipe_name: acquia_starterkit_place
    path: site_studio/pack_acquia_starterkit_place
  options:
    extra-validation: false
-
  type: default_recipe_package
  source:
    dependencies:
      modules:
        - acquia_cms_search
      recipes:
      - acquia_starterkit_place
    recipe_name: acquia_starterkit_place
    path: site_studio/pack_acquia_starterkit_place_search
  options:
    extra-validation: false
-
  type: default_recipe_package
  source:
    dependencies:
      recipes:
        - acquia_starterkit_event
    recipe_name: acquia_starterkit_event
    path: site_studio/pack_acquia_starterkit_event
  options:
    extra-validation: false
-
  type: default_recipe_package
  source:
    dependencies:
      modules:
        - acquia_cms_search
      recipes:
        - acquia_starterkit_event
    recipe_name: acquia_starterkit_event
    path: site_studio/pack_acquia_starterkit_event_search
  options:
    extra-validation: false
-
  type: default_recipe_package
  source:
    dependencies:
      recipes:
        - acquia_starterkit_person
    recipe_name: acquia_starterkit_person
    path: site_studio/pack_acquia_starterkit_person
  options:
    extra-validation: false
-
  type: default_recipe_package
  source:
    dependencies:
      modules:
        - acquia_cms_search
      recipes:
        - acquia_starterkit_person
    recipe_name: acquia_starterkit_person
    path: site_studio/pack_acquia_starterkit_person_search
  options:
    extra-validation: false
-
  type: default_recipe_package
  source:
    dependencies:
      recipes:
        - acquia_starterkit_article
    recipe_name: acquia_starterkit_article
    path: site_studio/pack_acquia_starterkit_article
  options:
    extra-validation: false
-
  type: default_recipe_package
  source:
    dependencies:
      modules:
        - acquia_cms_search
      recipes:
      - acquia_starterkit_article
    recipe_name: acquia_starterkit_article
    path: site_studio/pack_acquia_starterkit_article_search
  options:
    extra-validation: false
-
  type: default_recipe_package
  source:
    dependencies:
      recipes:
        - acquia_starterkit_dam
    recipe_name: acquia_starterkit_dam
    path: site_studio/pack_acquia_starterkit_dam
  options:
    extra-validation: false
-
  type: default_recipe_package
  source:
    dependencies:
      recipes:
        - acquia_starterkit_remote_audio
    recipe_name: acquia_starterkit_remote_audio
    path: site_studio/pack_acquia_starterkit_remote_audio
  options:
    extra-validation: false
