name: 'Acquia Drupal Startekit Image'
description: 'Provides an Image media type and related configuration.'
type: 'Starterkit addon'
install:
  # Contrib
  - acquia_cms_image
config:
  import:
    acquia_cms_image: '*'
    file: '*'
    image: '*'
    imce: '*'
    media: '*'
    media_library: '*'
    taxonomy: '*'
    field_group: '*'
    focal_point: '*'
