name: 'Acquia Drupal Startekit Person'
description: 'Provides a Person content type, a structured data representation of people associated with a website or organization.'
type: 'Starterkit addon'
install:
  # Contrib
  - acquia_cms_person
