third_party_settings:
  cohesion_sync_extras:
    export_enabled: true
    export_type: sync_module
    export_settings_sync_module:
      export_module_machine_name: acquia_cms_person
      export_exclude_config_dependencies: 1
      export_exclude_file_dependencies: 1
      export_separate_yaml_files: 1
      export_include_export_settings: 0
      export_update_module_dependencies: 0
