<?php

/**
 * @file
 * Contains hook implementations for the acquia_cms_tour module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\user\RoleInterface;

/**
 * Implements hook_menu_links_discovered_alter().
 */
function acquia_cms_tour_menu_links_discovered_alter(array &$links) {
  // Direct the Help link to our tour, leaving the help available to people who
  // know where it is.
  if (array_key_exists('help.main', $links)) {
    $links['help.main']['route_name'] = $links['acquia_cms_tour.tour']['route_name'];
    $links['help.main']['title'] = $links['acquia_cms_tour.tour']['title'];
    // Don't show our Tour link twice.
    unset($links['acquia_cms_tour.tour']);
  }
}

/**
 * Register tour twig file.
 *
 * Implements hook_theme().
 */
function acquia_cms_tour_theme() {
  return [
    'acquia_cms_tour_checklist_form' => [
      'render element' => 'form',
    ],
    'acquia_cms_tour_title_markup' => [
      'variables' => [
        'module_name' => NULL,
        'current_step' => NULL,
      ],
    ],
    'acquia_cms_starter_kit_title_markup' => [
      'variables' => [
        'label' => NULL,
      ],
    ],
  ];
}

/**
 * Remove configuration form state when module is uninstalled.
 *
 * Implements hook_modules_uninstalled().
 */
function acquia_cms_tour_modules_uninstalled(array $modules) {
  foreach ($modules as $module) {
    \Drupal::state()->delete('acms_' . $module . '_configured');
  }
}

/**
 * Implements hook_cms_tour_entity_insert().
 */
function acquia_cms_tour_user_role_insert(RoleInterface $role) {
  if(!$role->isSyncing() &&
    $role->id() == 'content_administrator'
  ) {
    $role = \Drupal::entityTypeManager()->getStorage('user_role')->load('content_administrator');
    $role->grantPermission('access acquia cms tour dashboard')->trustData()->save();
  }
}
