<?php

/**
 * @file
 * Contains hook implementations for the acquia_cms_tour module.
 */

/**
 * Implements hook_menu_links_discovered_alter().
 */
function acquia_cms_tour_menu_links_discovered_alter(array &$links) {
  // Direct the Help link to our tour, leaving the help available to people who
  // know where it is.
  if (array_key_exists('help.main', $links)) {
    $links['help.main']['route_name'] = $links['acquia_cms_tour.tour']['route_name'];
    $links['help.main']['title'] = $links['acquia_cms_tour.tour']['title'];
    // Don't show our Tour link twice.
    unset($links['acquia_cms_tour.tour']);
  }
}
