<?php

/**
 * @file
 * Drupal\Core\Form\FormStateInterface.
 */

/**
 * Implements hook_entity_type_alter().
 *
 * See https://drupal.stackexchange.com/a/192813/13414.
 */
function acquia_cms_headless_robustapi_entity_type_alter(array &$entity_types) {
  // @todo We can probably remove this as I don't believe we need to alter
  // the entity list views for consumers or next js sites.
  /** @var \Drupal\Core\Entity\EntityTypeInterface[] $entity_types */
  // $entity_types['consumer']->setListBuilderClass('Drupal\acquia_cms_headless_robustapi\HeadlessRobustConsumerListBuilder');
  // $entity_types['next_site']->setListBuilderClass('Drupal\acquia_cms_headless_robustapi\HeadlessRobustNextSiteListBuilder');
}
