<?php

/**
 * @file
 * Install, update and uninstall functions for the acquia_cms_video module.
 */

/**
 * Implements hook_entity_insert().
 */
function acquia_cms_video_entity_insert(EntityInterface $entity) {
  switch ($entity->id()) {
    case 'content_author':
      $role = \Drupal::entityTypeManager()->getStorage('user_role')->load($entity->id());
      foreach ([
        'create video media',
        'edit own video media',
        'delete own video media',
      ] as $permission) {
        $role->grantPermission($permission);
      }
      $role->trustData()->save();
      break;

    case 'content_editor':
      $role = \Drupal::entityTypeManager()->getStorage('user_role')->load($entity->id());
      foreach (['edit any video media', 'delete any video media'] as $permission) {
        $role->grantPermission($permission);
      }
      $role->trustData()->save();
      break;
  }
}
