<?php

/**
 * @file
 * Install, update and uninstall functions for the acquia_cms_video module.
 */

use Drupal\acquia_cms_video\EntityOperations\PermissionManager;
use Drupal\user\RoleInterface;

/**
 * Implements hook_entity_insert().
 */
function acquia_cms_video_user_role_insert(RoleInterface $role) {
  if(!$role->isSyncing()) {
    $class_resolver = \Drupal::service('class_resolver');
    $class_resolver->getInstanceFromDefinition(PermissionManager::class)
      ->grantPermissionToRoles([$role->id()]);
  }
}
