FROM docksal/cli:2.4-php7.2

RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
    apt-get update && \
    apt-get install ./google-chrome-stable_current_amd64.deb -y

EXPOSE 9222