name: 'Acquia Drupal Startekit Media Model'
description: 'An media model provides Audio, Document, Image< Video media types.'
type: 'Starterkit addon'
install:
  # Contrib
  - acquia_cms_audio
  - acquia_cms_document
  - acquia_cms_image
  - acquia_cms_video
