name: 'Acquia Drupal Startekit Content Model'
description: 'An content model provides Article, Event, Page, Person, Place content types.'
type: 'Starterkit addon'
recipes:
  - acquia_drupal_starterkit_article
  - acquia_drupal_starterkit_event
  - acquia_drupal_starterkit_page
