name: 'Acquia Drupal Startekit Low-Code'
description: 'An content model provides Article, Event, Page, Person, Place content types.'
type: 'Starterkit'
recipes:
  - acquia_drupal_starterkit_community
install:
  # Contrib
  - acquia_cms_site_studio
