<?php

/**
 * @file
 * Install, update and uninstall functions for the acquia_cms_image module.
 */

/**
 * Implements hook_entity_insert().
 */
function acquia_cms_image_entity_insert(EntityInterface $entity) {
  switch ($entity->id()) {
    case 'content_author':
      $role = \Drupal::entityTypeManager()->getStorage('user_role')->load($entity->id());
      foreach ([
        'create image media',
        'edit own image media',
        'delete own image media',
      ] as $permission) {
        $role->grantPermission($permission);
      }
      $role->trustData()->save();
      break;

    case 'content_editor':
      $role = \Drupal::entityTypeManager()->getStorage('user_role')->load($entity->id());
      foreach (['edit any image media', 'delete any image media'] as $permission) {
        $role->grantPermission($permission);
      }
      $role->trustData()->save();
      break;
  }
}
