<?php

use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\media\Entity\Media;

/**
 * The magic file entity UUID used by _acquia_cms_image_default_value().
 */
const ACQUIA_CMS_TEST_IMAGE_UUID = 'acquia-cms--test-image';

/**
 * Returns a default value for an entity reference.
 *
 * If a file entity exists with a magic UUID, a media entity will automatically
 * be created for it and used as the default value for the field. This is done
 * strictly for automated testing purposes and should NEVER be used in
 * production code. If you do, I swear I will find you and hit you over the head
 * with a rubber chicken.
 *
 * @param $entity
 *   The entity for which the default value is being computed.
 * @param \Drupal\Core\Field\FieldDefinitionInterface $field_definition
 *   The field definition.
 *
 * @return array
 *   The default value for the field.
 */
function _acquia_cms_image_default_value($entity, FieldDefinitionInterface $field_definition) {
  $file = Drupal::service('entity.repository')
    ->loadEntityByUuid('file', ACQUIA_CMS_TEST_IMAGE_UUID);

  if ($file) {
    $media = Media::create([
      'bundle' => 'image',
      'image' => $file->id(),
    ]);
    $media->save();

    return [
      [
        'target_id' => $media->id(),
      ],
    ];
  }
  else {
    return $field_definition->getDefaultValueLiteral();
  }
}
