acquia_cms_headless.settings:
  type: config_object
  label: 'Acquia CMS Headless settings'
  mapping:
    robust_api:
      type: boolean
      label: 'Enable Robust API capabilities'
    headless_mode:
      type: boolean
      label: 'Enable Headless mode'
    consumer_uuid:
      type: string
      label: 'Headless Consumer UUID'
    user_uuid:
      type: string
      label: 'Headless User UUID'
