acquia_cms_headless.settings:
  type: config_object
  label: 'Acquia CMS Headless settings'
  mapping:
    starterkit_nextjs:
      type: boolean
      label: 'Enable Next.js starter kit'
    headless_mode:
      type: boolean
      label: 'Enable Headless mode'
    consumer_uuid:
      type: string
      label: 'Headless Consumer UUID'
    user_uuid:
      type: string
      label: 'Headless User UUID'
