name: 'Acquia Drupal Startekit Search'
description: "Provides integration between your Drupal site and Acquia's hosted search service."
type: 'Starterkit addon'
install:
  # Contrib
  - acquia_cms_search
