include:
  ################
  # DrupalCI includes:
  # As long as you include this, any future includes added by the Acquia CMS will be accessible to your pipelines automatically.
  # View these include files at https://git.drupalcode.org/project/gitlab_orca/-/tree/acquia_cms/
  ################
  - project: "project/gitlab_orca"
    ref: "acquia_cms"
    file:
      - '/includes/include.orcaci.main.yml'
      - '/includes/include.orcaci.variables.yml'

variables:
  ORCA_SUT_NAME: drupal/acquia_cms_search
  ORCA_SUT_BRANCH: 1.x
  ORCA_PACKAGES_CONFIG_ALTER: $CI_PROJECT_DIR/tests/packages_alter.yml

  # The 1.6.x release of Acquia CMS Search  doesn't support Drupal 9.5.x.
  SKIP_INTEGRATED_TEST_ON_LATEST_EOL_MAJOR: 1
  SKIP_INTEGRATED_TEST_ON_LATEST_EOL_MAJOR_PHP8: 1
