<?php

/**
 * @file
 * Contains hook implementations for Acquia CMS Search.
 */

use Drupal\acquia_cms_search\Facade\SearchFacade;
use Drupal\Core\DestructableInterface;
use Drupal\node\NodeTypeInterface;
use Drupal\search_api\Entity\Index;
use Drupal\search_api\ServerInterface;

/**
 * Implements hook_ENTITY_TYPE_insert() for node types.
 */
function acquia_cms_search_node_type_insert(NodeTypeInterface $node_type) {
  Drupal::classResolver(SearchFacade::class)->addNodeType($node_type);
}

/**
 * Implements hook_entity_insert().
 */
function acquia_cms_search_entity_insert() {
  // Normally, content is indexed immediately after it is created or modified,
  // at the end of the current request. But that means content created
  // programmatically (i.e., in the PHPUnit tests) are not being indexed. So,
  // explicitly invoke the indexer whenever an entity is created.
  $indexer = Drupal::service('search_api.post_request_indexing');
  if ($indexer instanceof DestructableInterface) {
    $indexer->destruct();
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert() for Search API servers.
 */
function acquia_cms_search_search_api_server_insert(ServerInterface $server) {
  // We don't want to do any secondary config writes during a config sync,
  // since that can have major, unintentional side effects.
  if (Drupal::isConfigSyncing()) {
    return;
  }

  // Look for an index which is disabled, but wants to passively opt into using
  // this server.
  $indexes = Index::loadMultiple();
  /** @var \Drupal\search_api\IndexInterface $index */
  foreach ($indexes as $index) {
    if ($index->status() || $index->isServerEnabled()) {
      continue;
    }

    // If the index wants to opt into using this server, grant its wish.
    $server_name = $index->getThirdPartySetting('acquia_cms', 'search_server');
    if ($server_name && $server->id() === $server_name) {
      $index->setServer($server)
        ->enable()
        // The third-party setting is only needed once.
        ->unsetThirdPartySetting('acquia_cms', 'search_server')
        ->save();
    }
  }
}

/**
 * Implements hook_config_schema_info_alter().
 */
function acquia_cms_search_config_schema_info_alter(array &$definitions) {
  // Allow node types to carry a 'search_index' setting. This is used by our
  // facade to passively opt the node type into a particular index.
  // @see acquia_cms_search_node_type_insert()
  // @see \Drupal\acquia_cms_search\Facade\SearchFacade::addNodeType()
  $definitions['node.type.*.third_party.acquia_cms']['mapping']['search_index'] = [
    'type' => 'string',
    'label' => 'The machine name of the search index to which this content type should be added',
  ];
}
