<?php

/**
 * @file
 * Contains hook implementations for common, shared Acquia CMS functionality.
 */

use Drupal\acquia_cms_common\Facade\MetatagFacade;
use Drupal\acquia_cms_common\Facade\WorkbenchEmailFacade;
use Drupal\acquia_cms_common\Facade\WorkflowFacade;
use Drupal\Core\Form\FormStateInterface;
use Drupal\imce\Imce;
use Drupal\node\NodeTypeInterface;
use Drupal\workbench_email\TemplateInterface;

/**
 * Implements hook_ENTITY_TYPE_insert() for node types.
 */
function acquia_cms_common_node_type_insert(NodeTypeInterface $node_type) {
  Drupal::classResolver(WorkflowFacade::class)->addNodeType($node_type);
  Drupal::classResolver(MetatagFacade::class)->addNodeType($node_type);
}

/**
 * Implements hook_ENTITY_TYPE_insert() for template types.
 */
function acquia_cms_common_workbench_email_template_insert(TemplateInterface $template_type) {
  Drupal::classResolver(WorkbenchEmailFacade::class)
    ->addTemplate($template_type);
}

/**
 * Implements hook_preprocess_HOOK() for html.
 */
function acquia_cms_common_preprocess_html(&$variables) {
  $path = Drupal::service('path.current')->getPath();
  if (Imce::access() && $path == '/imce') {
    $variables['attributes']['class'][] = 'acquia-cms';
    $variables['#attached']['library'][] = 'acquia_cms_common/imce';
  }
}

/**
 * Implements hook_form_alter() for html.
 */
function acquia_cms_common_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'views_exposed_form') {
    $form['edit-keywords-label'] = [
      '#type' => 'markup',
      '#markup' => '<label for="edit-keywords" class="visually-hidden">' . t('Search') . '</label>',
      '#allowed_tags' => [
        'label',
      ],
    ];
  }
}

/**
 * Implements hook_views_data().
 */
function acquia_cms_common_views_data() {
  return [
    'views' => [
      'main_listing_pages_view' => [
        'title' => t('Main listing pages - Text area'),
        'help' => t('Insert a text area inside a main view listing pages if the search server is available. If the view is not based on a Search API index, this behaves like a standard text area.'),
        'area' => [
          'id' => 'main_listing_pages_view',
        ],
      ],
    ],
  ];
}
