<?php

/**
 * @file
 * Contains hook implementations for common, shared Acquia CMS functionality.
 */

use Drupal\acquia_cms_common\Facade\MetatagFacade;
use Drupal\acquia_cms_common\Facade\WorkbenchEmailFacade;
use Drupal\acquia_cms_common\Facade\WorkflowFacade;
use Drupal\imce\Imce;
use Drupal\node\NodeTypeInterface;
use Drupal\views\ViewExecutable;
use Drupal\workbench_email\TemplateInterface;

/**
 * Implements hook_ENTITY_TYPE_insert() for node types.
 */
function acquia_cms_common_node_type_insert(NodeTypeInterface $node_type) {
  Drupal::classResolver(WorkflowFacade::class)->addNodeType($node_type);
  Drupal::classResolver(MetatagFacade::class)->addNodeType($node_type);
}

/**
 * Implements hook_ENTITY_TYPE_insert() for template types.
 */
function acquia_cms_common_workbench_email_template_insert(TemplateInterface $template_type) {
  Drupal::classResolver(WorkbenchEmailFacade::class)
    ->addTemplate($template_type);
}

/**
 * Implements hook_preprocess_HOOK() for html.
 */
function acquia_cms_common_preprocess_html(&$variables) {
  $path = Drupal::service('path.current')->getPath();
  if (Imce::access() && $path == '/imce') {
    $variables['attributes']['class'][] = 'acquia-cms';
    $variables['#attached']['library'][] = 'acquia_cms_common/imce';
  }
}

/**
 * Implements hook_views_pre_render().
 */
function acquia_cms_common_views_pre_render(ViewExecutable $view) {
  $search_pages = ['articles', 'search', 'events', 'people', 'places'];
  if (in_array($view->id(), $search_pages)) {
    $view->element['#attached']['library'][] = 'acquia_cms_common/page';
  }
}
