<?php

/**
 * @file
 * Contains hook implementations for Acquia Pubsec Demo.
 */

/**
 * Implements hook_preprocess_HOOK() for html.
 */
function acquia_cms_demo_pubsec_preprocess_html(&$variables) {
  $variables['#attached']['library'][] = 'acquia_cms_demo_pubsec/pubsec_styles';
}

/**
 * Implements hook_preprocess_HOOK() for html.
 */
function acquia_cms_demo_pubsec_preprocess_page__system__404(&$variables) {
  $variables['message'] = t('Looks like you took a wrong turn in Acquiaville. <p> We can’t find the page you’re looking for, try going in one of these directions instead:</p>');
  $variables['button_search'] = t('SEARCH PAGE');
}
