<?php

/**
 * @file
 * Functions to support Acquia CMS toolbar.
 */

use Acquia\DrupalEnvironmentDetector\AcquiaDrupalEnvironmentDetector as Environment;
use Drupal\Core\Render\Markup;
use Drupal\Core\Url;

/**
 * Implements hook_preprocess_HOOK().
 */
function acquia_cms_toolbar_preprocess_html(array &$variables) {
  $variables['attributes']['class'][] = 'acquia-cms-toolbar';
}

/**
 * Implements hook_toolbar_alter().
 */
function acquia_cms_toolbar_toolbar_alter(array &$items) {
  if (isset($items['user'], $items['admin_toolbar_tools'])) {
    $items['user']['#wrapper_attributes']['class'] = ['user-toolbar-tab'];
    $items['admin_toolbar_tools']['#attached']['library'][] = 'acquia_cms_toolbar/styling';
  }
}

/**
 * Implements hook_toolbar().
 */
function acquia_cms_toolbar_toolbar() {
  $environment_indicator_settings = get_environment_indicator_color_config();
  $items['environment_indicator'] = [
    '#type' => 'toolbar_item',
    '#weight' => 125,
    'tab' => [
      '#type' => 'link',
      '#title' => $environment_indicator_settings['name'],
      '#url' => Url::fromRoute('<front>'),
      '#attributes' => [
        'title' => t('Environments'),
        'class' => [
          'toolbar-icon',
          'toolbar-icon-environment',
        ],
      ],
    ],
  ];

  return $items;
}

/**
 * Implements hook_page_attachments().
 */
function acquia_cms_toolbar_page_attachments(array &$page): void {
  // Add css variables for environment indicator colors.
  $environment_settings = get_environment_indicator_color_config();
  $style = ':root {--env-background:' . $environment_settings['bg_color'] .
    '; --env-text-color:' . $environment_settings['text_color'] . ' } ';
  $page['#attached']['html_head'][] = [
    [
      '#tag' => 'style',
      '#value' => Markup::create($style),
    ],
  ];
}

/**
 * Get environment indicator settings for current environment.
 *
 * @return array
 *   name => 'Local' // Environment name
 *   bg_color => '#1078C2' // Background color for env indicator menu item
 *   text_color => '#FFFFFF' // Text color for env indicator menu item
 */
function get_environment_indicator_color_config() : array {
  if (Environment::isAhEnv()) {
    $environment_indicator['name'] = ucfirst(Environment::getAhEnv());
    $environment_indicator['text_color'] = '#FFFFFF';

    if (Environment::isAhIdeEnv()) {
      $environment_indicator['bg_color'] = '#1078C2';
    }

    if (Environment::isAhDevEnv()) {
      $environment_indicator['bg_color'] = '#498414';
    }

    if (Environment::isAhStageEnv()) {
      $environment_indicator['bg_color'] = '#FEB32B';
      $environment_indicator['text_color'] = '#000000';
    }

    if (Environment::isAhProdEnv()) {
      $environment_indicator['bg_color'] = '#CD3A3D';
    }
  }
  else {
    $environment_indicator['name'] = 'Local';
    $environment_indicator['bg_color'] = '#1078C2';
  }

  return $environment_indicator;
}
