<?php

/**
 * @file
 * Functions to support Acquia CMS toolbar.
 */

use Acquia\DrupalEnvironmentDetector\AcquiaDrupalEnvironmentDetector as Environment;
use Drupal\acquia_cms_toolbar\EntityOperations\PermissionManager;
use Drupal\Core\Url;
use Drupal\user\RoleInterface;

/**
 * Implements hook_preprocess_HOOK().
 */
function acquia_cms_toolbar_preprocess_html(array &$variables) {
  $environment_indicator_settings = _acquia_cms_toolbar_get_environment_indicator_color_config();
  $variables['attributes']['class'][] = 'acquia-cms-toolbar';
  $variables['attributes']['class'][] = 'acquia-cms-' . $environment_indicator_settings['environment'];
}

/**
 * Implements hook_preprocess_HOOK() for page.
 */
function acquia_cms_toolbar_preprocess_page(&$variables) {
  $toolbar_access = \Drupal::currentUser()->hasPermission('access toolbar') ?? FALSE;

  // Check if user has access to admin toolbar and its not admin route.
  if ($toolbar_access) {
    // Attach toolbar styles library on all pages.
    $variables['#attached']['library'][] = 'acquia_cms_toolbar/toolbar_styles';
  }
}

/**
 * Implements hook_toolbar_alter().
 */
function acquia_cms_toolbar_toolbar_alter(array &$items) {
  if (isset($items['user'], $items['admin_toolbar_tools'])) {
    $items['user']['#wrapper_attributes']['class'] = ['user-toolbar-tab'];
    $items['admin_toolbar_tools']['#attached']['library'][] = 'acquia_cms_toolbar/styling';
  }
}

/**
 * Implements hook_toolbar().
 */
function acquia_cms_toolbar_toolbar() {
  $environment_indicator_settings = _acquia_cms_toolbar_get_environment_indicator_color_config();
  $items['environment_indicator'] = [
    '#type' => 'toolbar_item',
    '#weight' => 125,
    'tab' => [
      '#type' => 'link',
      '#title' => $environment_indicator_settings['name'],
      '#url' => Url::fromRoute('<front>'),
      '#attributes' => [
        'title' => t('Environments'),
        'class' => [
          'toolbar-icon',
          'toolbar-icon-environment',
          $environment_indicator_settings['environment'],
        ],
      ],
    ],
  ];

  return $items;
}

/**
 * Get environment indicator settings for current environment.
 *
 * @return array
 *   name => 'Local' // Environment name
 *   environment => 'environment-ide' // CSS class name
 */
function _acquia_cms_toolbar_get_environment_indicator_color_config(): array {
  $environment_indicator['name'] = 'Local';
  $environment_indicator['environment'] = 'environment-local';

  if (Environment::isAhEnv()) {
    $environment_indicator['name'] = ucfirst(Environment::getAhEnv());

    if (Environment::isAhIdeEnv()) {
      $environment_indicator['environment'] = 'environment-ide';
    }

    if (Environment::isAhDevEnv()) {
      $environment_indicator['environment'] = 'environment-dev';
    }

    if (Environment::isAhStageEnv()) {
      $environment_indicator['environment'] = 'environment-stage';
    }

    if (Environment::isAhProdEnv()) {
      $environment_indicator['environment'] = 'environment-prod';
    }
  }

  return $environment_indicator;
}

/**
 * Implements hook_entity_insert().
 */
function acquia_cms_toolbar_user_role_insert(RoleInterface $role) {
  if (!$role->isSyncing()) {
    $class_resolver = \Drupal::service('class_resolver');
    $class_resolver->getInstanceFromDefinition(PermissionManager::class)
      ->grantPermissionToRoles([$role->id()]);
  }
}
