<?php

/**
 * @file
 * Functions to support Acquia CMS toolbar.
 */

use Acquia\DrupalEnvironmentDetector\AcquiaDrupalEnvironmentDetector as EnvironmentDetector;
use Drupal\Core\Render\Markup;
use Drupal\Core\Url;

/**
 * Implements hook_preprocess_HOOK().
 */
function acquia_cms_toolbar_preprocess_html(array &$variables) {
  $variables['attributes']['class'][] = 'acquia-cms-toolbar';
}

/**
 * Implements hook_toolbar_alter().
 */
function acquia_cms_toolbar_toolbar_alter(array &$items) {
  if (isset($items['user'], $items['admin_toolbar_tools'])) {
    $items['user']['#wrapper_attributes']['class'] = ['user-toolbar-tab'];
    $items['admin_toolbar_tools']['#attached']['library'][] = 'acquia_cms_toolbar/styling';
  }
}

/**
 * Implements hook_toolbar().
 */
function acquia_cms_toolbar_toolbar() {
  $environment_indicator_settings = environment_indicator_color_config();
  $items['environment_indicator'] = [
    '#type' => 'toolbar_item',
    '#weight' => 125,
    'tab' => [
      '#type' => 'link',
      '#title' => $environment_indicator_settings['name'],
      '#url' => Url::fromRoute('acquia_cms_toolbar.settings'),
      '#attributes' => [
        'title' => t('Environments'),
        'class' => [
          'toolbar-icon',
          'toolbar-icon-environment',
        ],
      ],
    ],
  ];

  return $items;
}

/**
 * Implements hook_page_attachments().
 */
function acquia_cms_toolbar_page_attachments(&$page) {
  // Add a css variable for environment indicator color.
  $environment_settings = environment_indicator_color_config();
  $style = ':root {--env-background:' . $environment_settings['bg_color'] .
    '; --env-text-color:' . $environment_settings['text_color'] . ' } ';
  $page['#attached']['html_head'][] = [
    [
      '#tag' => 'style',
      '#value' => Markup::create($style),
    ],
  ];
}

/**
 * Get color configuration for current environment.
 */
function environment_indicator_color_config() {
  if (EnvironmentDetector::isAhEnv()) {
    $environment_indicator['name'] = ucfirst($_ENV['AH_SITE_ENVIRONMENT']);

    if (EnvironmentDetector::isAhIdeEnv()) {
      $environment_indicator['bg_color'] = '#1078C2';
      $environment_indicator['text_color'] = '#FFFFFF';
    }

    if (EnvironmentDetector::isAhDevEnv()) {
      $environment_indicator['bg_color'] = '#498414';
      $environment_indicator['text_color'] = '#FFFFFF';
    }

    if (EnvironmentDetector::isAhStageEnv()) {
      $environment_indicator['bg_color'] = '#FEB32B';
      $environment_indicator['text_color'] = '#000000';
    }

    if (EnvironmentDetector::isAhProdEnv()) {
      $environment_indicator['bg_color'] = '#CD3A3D';
      $environment_indicator['text_color'] = '#FFFFFF';
    }
  }
  else {
    $environment_indicator['name'] = 'Local';
    $environment_indicator['bg_color'] = '#1078C2';
    $environment_indicator['text_color'] = '#FFFFFF';
  }

  return $environment_indicator;
}
