<?php

/**
 * @file
 * Install, update and uninstall functions for the acquia_cms_audio module.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_content_model_role_presave_alter().
 */
function acquia_cms_audio_entity_insert(EntityInterface $entity) {
  switch ($entity->id()) {
    case 'content_author':
      $role = \Drupal::entityTypeManager()->getStorage('user_role')->load($entity->id());
      foreach ([
        'create audio media',
        'edit own audio media',
        'delete own audio media',
      ] as $permission) {
        $role->grantPermission($permission);
      }
      $role->trustData()->save();
      break;

    case 'content_editor':
      $role = \Drupal::entityTypeManager()->getStorage('user_role')->load($entity->id());
      foreach (['edit any audio media', 'delete any audio media'] as $permission) {
        $role->grantPermission($permission);
      }
      $role->trustData()->save();
      break;
  }
}
