name: 'Acquia Drupal Startekit Video'
description: 'Provides a Video media type and related configuration.'
type: 'Starterkit addon'
install:
  # Contrib
  - acquia_cms_video
config:
  import:
    acquia_cms_video: '*'
    file: '*'
    media: '*'
    media_library: '*'
    taxonomy: '*'
    field_group: '*'
