<?php

/**
 * @file
 * Contains hook implementations for config management.
 */

use Symfony\Component\Yaml\Yaml;

/**
 * Helper function to get configurations.
 *
 * @param string $config
 *   The name of configuration.
 * @param string $module
 *   The name of module.
 */
function _sitestudio_config_management_get_configuration(string $config, string $module): array {
  $module_path = \Drupal::service('extension.list.module')->getPath($module);
  $module_path .= '/config/optional/' . $config . '.yml';
  $content = file_get_contents($module_path);
  return Yaml::parse($content);
}
