<?php

/**
 * @file
 * Contains hook implementations for config management.
 */

use Symfony\Component\Yaml\Yaml;

/**
 * Helper function to import configurations.
 *
 * @param string $config
 *   The name of configuration.
 * @param string $module
 *   The name of module.
 */
function _sitestudio_config_management_import_configuration(string $config, string $module) {
  $module_path = \Drupal::service('extension.list.module')->getPath($module);
  $module_path .= '/config/optional/' . $config . '.yml';
  $content = file_get_contents($module_path);
  $parsed_yml = Yaml::parse($content);
  return $parsed_yml;
}
