services:
  acquia_cms_config_management.site_install:
    class: Drupal\acquia_cms_config_management\SiteInstall
  acquia_cms_config_management.post_config_export_acquia:
    class: '\Drupal\acquia_cms_config_management\EventSubscriber\AcquiaPostConfigExport'
    tags:
      - { name: 'event_subscriber' }
