# Uncomment below lines to activate the variables.
#web_environment:
#  - SITESTUDIO_API_KEY=<xxx-xxx-xxx>
#  - SITESTUDIO_ORG_KEY=<xxx-xxx-xxx>
#  - CONNECTOR_ID=<xxx-xxx-xxx>
#  - SEARCH_UUID=<xxx-xxx-xxx-xxx>
#  - CONNECTOR_KEY=<xxx-xxx-xxx-xxx>
#  - CLOUD_API_KEY=<xxx-xxx-xxx-xxx>
#  - CLOUD_API_SECRET=<xxx-xxx-xxx-xxx>
#  - GMAPS_KEY=<xxx-xxx-xxx-xxx>
