name: 'Acquia Drupal Startekit Community'
description: 'The community starter kit will install Acquia Drupal Starterkit.'
type: 'Starterkit'
install:
  # Contrib
  - acquia_cms_toolbar
  - acquia_cms_tour

