- config/dx8/cohesion_content_templates.media_image_embedded.yml_
- config/dx8/cohesion_content_templates.media_image_full.yml_
- config/dx8/cohesion_content_templates.media_image_large.yml_
- config/dx8/cohesion_content_templates.media_image_large_landscape.yml_
- config/dx8/cohesion_content_templates.media_image_medium.yml_
- config/dx8/cohesion_content_templates.media_image_medium_landscape.yml_
- config/dx8/cohesion_content_templates.media_image_small.yml_
- config/dx8/cohesion_content_templates.media_image_small_landscape.yml_
